name: Deploy

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install    
      - run: npm run build

      - name: Deploy
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: build
          container_name: $web
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          overwrite: 'true'

  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/github-script@v3
          with:
            github-token: ${{ github.token }}
            script: |
              github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/prod-${new Date().toISOString().replace(/[^0-9T]/g, "")}`,
                sha: context.sha
              })